### ISSUE TITLE
Textures for thermal foundation/expansion

### ISSUE THREAD

**Issue by VoidFyre** [John-Smith-Modded/JSTR-Modded-1.10.x#14]
The textures for the active redstone furnaces are either nonexistent or not working, because whenever they are active they have the untextured pink and black look to them.

**Comment by Oddface** [comment]
Some bad .mcmeta files in there for a few machines. It's been fixed. Thanks for reporting!

**Comment by VoidFyre** [comment]
when will you be posting the fixed version?

**Comment by Oddface** [comment]
Not sure. It's up to @artdude543 who has to run the script to compile the packs manually since the automated system is down. If you want a fix immediately you can take the files from the repository and put them in the pack yourself. The files I fixed are here: https://github.com/John-Smith-Modded/JSTR-Modded-1.10.x/tree/master/Thermal_Expansion/assets/thermalexpansion/textures/blocks/machine
